#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xE81444E9CE1F695D (wolph@wol.ph)
#
Name     : python-utils
Version  : 2.3.0
Release  : 7
URL      : https://github.com/WoLpH/python-utils/releases/download/v2.3.0/python-utils-v2.3.0.tar.xz
Source0  : https://github.com/WoLpH/python-utils/releases/download/v2.3.0/python-utils-v2.3.0.tar.xz
Source1  : https://github.com/WoLpH/python-utils/releases/download/v2.3.0/python-utils-v2.3.0.tar.xz.asc
Summary  : A module with some convenient utilities not included with the standard Python install
Group    : Development/Tools
License  : BSD-3-Clause
Requires: python-utils-license = %{version}-%{release}
Requires: python-utils-python = %{version}-%{release}
Requires: python-utils-python3 = %{version}-%{release}
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : pytest-runner
BuildRequires : six
BuildRequires : tox
BuildRequires : virtualenv

%description
Useful Python Utils
==============================================================================

.. image:: https://travis-ci.org/WoLpH/python-utils.svg?branch=master
  :target: https://travis-ci.org/WoLpH/python-utils

.. image:: https://coveralls.io/repos/WoLpH/python-utils/badge.svg?branch=master
  :target: https://coveralls.io/r/WoLpH/python-utils?branch=master

Python Utils is a collection of small Python functions and
classes which make common patterns shorter and easier. It is by no means a
complete collection but it has served me quite a bit in the past and I will
keep extending it.

One of the libraries using Python Utils is Django Utils.

Documentation is available at: https://python-utils.readthedocs.org/en/latest/

Links
-----

 - The source: https://github.com/WoLpH/python-utils
 - Project page: https://pypi.python.org/pypi/python-utils
 - Reporting bugs: https://github.com/WoLpH/python-utils/issues
 - Documentation: https://python-utils.readthedocs.io/en/latest/
 - My blog: https://wol.ph/

Requirements for installing:
------------------------------------------------------------------------------

 - `six` any recent version

Installation:
------------------------------------------------------------------------------

The package can be installed through `pip` (this is the recommended method):

    pip install python-utils
    
Or if `pip` is not available, `easy_install` should work as well:

    easy_install python-utils
    
Or download the latest release from Pypi (https://pypi.python.org/pypi/python-utils) or Github.

Note that the releases on Pypi are signed with my GPG key (https://pgp.mit.edu/pks/lookup?op=vindex&search=0xE81444E9CE1F695D) and can be checked using GPG:

     gpg --verify python-utils-<version>.tar.gz.asc python-utils-<version>.tar.gz

Quickstart
------------------------------------------------------------------------------

This module makes it easy to execute common tasks in Python scripts such as
converting text to numbers and making sure a string is in unicode or bytes
format.

Examples
------------------------------------------------------------------------------

To extract a number from nearly every string:

.. code-block:: python

    from python_utils import converters

    number = converters.to_int('spam15eggs')
    assert number == 15

    number = converters.to_int('spam')
    assert number == 0

    number = converters.to_int('spam', default=1)
    assert number == 1

    number = converters.to_float('spam1.234')

To do a global import programmatically you can use the `import_global`
function. This effectively emulates a `from ... import *`

.. code-block:: python

    from python_utils.import_ import import_global

    # The following is  the equivalent of `from some_module import *`
    import_global('some_module')

Or add a correclty named logger to your classes which can be easily accessed:

.. code-block:: python

    class MyClass(Logged):
        def __init__(self):
            Logged.__init__(self)

    my_class = MyClass()

    # Accessing the logging method:
    my_class.error('error')

    # With formatting:
    my_class.error('The logger supports %(formatting)s',
                   formatting='named parameters')

    # Or to access the actual log function (overwriting the log formatting can
    # be done n the log method)
    import logging
    my_class.log(logging.ERROR, 'log')

%package license
Summary: license components for the python-utils package.
Group: Default

%description license
license components for the python-utils package.


%package python
Summary: python components for the python-utils package.
Group: Default
Requires: python-utils-python3 = %{version}-%{release}

%description python
python components for the python-utils package.


%package python3
Summary: python3 components for the python-utils package.
Group: Default
Requires: python3-core
Provides: pypi(python-utils)

%description python3
python3 components for the python-utils package.


%prep
%setup -q -n python-utils-v2.3.0
cd %{_builddir}/python-utils-v2.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583215723
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python-utils
cp %{_builddir}/python-utils-v2.3.0/LICENSE %{buildroot}/usr/share/package-licenses/python-utils/79255442d9b00df6f7c6c074743bc4a2236f83ee
cp %{_builddir}/python-utils-v2.3.0/docs/_theme/LICENSE %{buildroot}/usr/share/package-licenses/python-utils/3d1c6f6ce9ac9fdbae7bdc2b4d63940561f79edd
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python-utils/3d1c6f6ce9ac9fdbae7bdc2b4d63940561f79edd
/usr/share/package-licenses/python-utils/79255442d9b00df6f7c6c074743bc4a2236f83ee

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
